### ISSUE TITLE
NameError: uninitialized constant GSMEncoder::BS (NameError)

### ISSUE THREAD

**Issue by lucasmello** [yury/gsm_encoder#12]
Hello,

After upgrading the gem to version 0.1.7, the build failed in the `assets:precompile` phase (I'm using Rails 6). 

Here's the stacktrace:

```
6.740 NameError: uninitialized constant GSMEncoder::BS (NameError)
6.740 /app/config/initializers/gsm_encoder.rb:12:in `<module:GSMEncoder>'
6.740 /app/config/initializers/gsm_encoder.rb:8:in `<top (required)>'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/engine.rb:681:in `block in load_config_initializer'
6.740 /usr/local/bundle/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:205:in `instrument'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/engine.rb:680:in `load_config_initializer'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/engine.rb:633:in `each'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/engine.rb:633:in `block in <class:Engine>'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
6.740 /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'

```

Thank you for your assistance!

**Comment by yury** [comment]
what was that?

**Comment by yury** [comment]
Everything is ok?

**Comment by lucasmello** [comment]
Our initializer had a weird setup, so I fixed it on our side. Sorry for the trouble!
